version: '3.7'
services:
  srv:
    build: .
    ports:
      - "28785:28785/tcp"
      - "28785:28785/udp"
      - "28786:28786/tcp"
      - "28786:28786/udp"
    volumes:
      - "${PWD}/server-init.cfg/.sauerbraten/server-init.cfg"
